# ----
# Site

title: Lads Vape Liquids
url: "https://www.ladsvape.nz/"
baseurl:
cacheversion: v1

source: src
destination: _site

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: "Lad's Vape Liquids"
author:
  name: Lad's Vape
  email: ladsvape@gmail.com
social:
  name: David Graeff, Lun Tan
  links:
    - https://facebook.com/ladsvape

# -----
# Build

collections:
  products:
    _hide_content: true
    output: true

permalink: pretty

jekyll-archives:
  enabled:
    - categories

# http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: []
  endings: []
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

assets:
  compress:
    css: true
    js: false
  cache: .asset-cache
  prefix: "/assets"
  assets:
    - "*.png"
    - "screen.css"
    - "sw.js"
  digest: false
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-assets

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - node_modules
  - package.json
  - build.js
  - webpack.config.js
