# ----
# Site

title: Lads Vape Liquids
url: "https://www.ladsvape.nz/"
baseurl:
google_analytics_key: "UA-99603278-1"
google_maps_javascript_api_key: "AIzaSyAKfRbVaqwClJeRXqW_MDZ4Ra1iRFXb6xQ"
snipcart_key: "NWNjOWZhYjctYmE1ZS00MDM3LThkNjUtZmE5M2NiMTU1NzAwNjM2MjYzNTE1MzM5ODg1ODkw"

source: src
destination: _site

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: "Lad's Vape Liquids"
author:
  name: Lad's Vape
  email: ladsvape@gmail.com
social:
  name: David Graeff, Lun Tan
  links:
    - https://facebook.com/ladsvape

# -----
# Build

collections:
  products:
    _hide_content: true
    output: true

permalink: pretty

jekyll-archives:
  enabled:
    - categories

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - node_modules
