# ----
# Site

title: Lads Vape Liquids
url: https://www.ladsvape.nz
baseurl:
cacheversion: v1

source: src
destination: _site

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: "Lad's Vape Liquids"
author:
  name: Lad's Vape
  email: ladsvape@gmail.com
social:
  name: David Graeff, Lun Tan
  links:
    - https://facebook.com/ladsvape

# TODO fill details in here for better search engine indexing
#facebook:
# app_id: 1234
# publisher: 1234
#webmaster_verifications:
#  google: 1234
#  bing: 1234
#  alexa: 1234
#  yandex: 1234

# -----
# Build

collections:
  products:
    _hide_content: true
    output: true

permalink: pretty

jekyll-archives:
  enabled:
    - categories

# Add include directory
includes:
- _assets/css

# Compress html
# http://jch.penibelst.de/
compress_html:
  clippings: all
  comments: []
  endings: []
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

# Compress styles (for inlining)
scss:
  style: compressed

# Compress styles and selected javascript files
assets:
  compress:
    css: true
    js: true
  cache: .asset-cache
  prefix: "/assets"
  assets:
    - "screen.css"
    - "sw.js"
  digest: false
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-assets

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - node_modules
  - package.json
  - build.js
  - webpack.config.js
